#/.pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # For Django (Backend)
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ['--line-length=100']  # Optional: Adjust black settings if needed
        files: ^backend/  # Only run black on the backend directory
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=100',
          '--ignore=E203,W503',
          '--per-file-ignores=__init__.py:F401'
        ]
        files: ^backend/  # Only run flake8 on the backend directory

  # For Next.js (Frontend)
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.26.0
    hooks:
      - id: eslint
        files: ^frontend/  # Only run eslint on the frontend directory
        additional_dependencies:
          - eslint@9.22.0
          - eslint-config-next@15.2.2
          - eslint-plugin-prettier@5.2.3
          - eslint-config-prettier@10.1.1
        args: [
          '--config', 'frontend/eslint.config.mjs',
          '--fix',
          '--ext', '.ts,.tsx'
        ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/  # Only run prettier on the frontend directory
