#/docker-compose.yml
services:
  # Service for PostgreSQL database
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/db:/var/lib/postgresql/data/:z
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_db.local

  # Service for Next.js frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend:z
      - node_modules:/app/frontend/node_modules:z
    depends_on:
      - backend
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_frontend.local

  # Service for Django backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app/backend:z
      - ./static:/app/backend/static:z
    depends_on:
      - db
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_backend.local

networks:
  custom_network:
    name: ${PROJECT_NAME}
    driver: bridge

volumes:
  node_modules:
    driver: local
