# Generated by Django 5.1.7 on 2025-05-11 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("media", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("openverse_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("indexed_on", models.DateTimeField()),
                ("foreign_landing_url", models.URLField()),
                ("url", models.URLField()),
                ("creator", models.CharField(max_length=255, null=True)),
                ("creator_url", models.URLField(null=True)),
                ("license", models.CharField(max_length=50)),
                ("license_version", models.CharField(max_length=25, null=True)),
                ("license_url", models.URLField()),
                ("attribution", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=80, null=True)),
                ("file_size", models.IntegerField(null=True)),
                ("file_type", models.CharField(max_length=80, null=True)),
                ("mature", models.BooleanField()),
                ("thumbnail_url", models.URLField()),
                ("height", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("duration", models.IntegerField(null=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("audio", "Audio")], max_length=10
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "media",
                "verbose_name_plural": "media",
                "db_table": "media",
                "ordering": ["-indexed_on"],
                "indexes": [models.Index(fields=["title"], name="media_title_idx")],
            },
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.media"
                    ),
                ),
            ],
            options={
                "verbose_name": "favourite",
                "verbose_name_plural": "favourites",
                "db_table": "favourites",
                "ordering": ["-added_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "media"), name="unique_favourite")
                ],
            },
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.media"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="media.tag"),
                ),
            ],
            options={
                "verbose_name": "media tag",
                "verbose_name_plural": "media tags",
                "db_table": "media_tags",
                "constraints": [
                    models.UniqueConstraint(fields=("media", "tag"), name="unique_media_tag")
                ],
            },
        ),
    ]
