# Generated by Django 5.1.7 on 2025-05-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="thumbnail_url",
            field=models.URLField(null=True),
        ),
    ]
