# Generated by Django 5.1.7 on 2025-05-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_alter_media_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="attribution",
            field=models.CharField(max_length=1000),
        ),
    ]
