# Generated by Django 5.1.7 on 2025-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_alter_media_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="creator_url",
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="duration",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="file_size",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="foreign_landing_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="media",
            name="height",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="license_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="media",
            name="thumbnail_url",
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="media",
            name="width",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
