# Generated by Django 5.1.7 on 2025-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0007_alter_media_creator_url_alter_media_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="source",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
