# Generated by Django 5.1.7 on 2025-05-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0008_media_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediatag",
            name="accuracy",
            field=models.FloatField(default=0.0),
        ),
    ]
