# Generated by Django 5.1.7 on 2025-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0009_mediatag_accuracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="creator",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
