# Generated by Django 5.1.7 on 2025-05-26 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0010_alter_media_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_media",
                        to="media.media",
                    ),
                ),
                (
                    "related_media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="media.media",
                    ),
                ),
            ],
            options={
                "db_table": "related_media",
                "indexes": [
                    models.Index(fields=["media"], name="related_media_media_idx"),
                    models.Index(fields=["related_media"], name="related_media_rel_idx"),
                ],
                "unique_together": {("media", "related_media")},
            },
        ),
    ]
