# Generated by Django 5.1.7 on 2025-05-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0011_relatedmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="attribution",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="creator",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="creator_url",
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="license_url",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="media",
            name="thumbnail_url",
            field=models.URLField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="media",
            name="title",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="media",
            name="url",
            field=models.URLField(max_length=1024),
        ),
    ]
