# Generated by Django 5.1.7 on 2025-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchhistory",
            old_name="query",
            new_name="search_value",
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="search_key",
            field=models.CharField(default="q", max_length=10),
        ),
    ]
