// src/lib/search/mockData.ts

import type { SearchResult } from '@/lib/search/types'

export const mockData: SearchResult[] = [
  {
    id: '1',
    title: `First result`,
    description: 'A placeholder description.',
    url: `/media/1`,
    imageUrl: '/placeholder-1.jpg',
    type: 'image',
    date: '2025-05-01',
  },
  {
    id: '2',
    title: `Second result`,
    description: 'Another placeholder.',
    url: `/media/2`,
    imageUrl: '/placeholder-2.jpg',
    type: 'video',
    date: '2025-04-28',
  },
  {
    id: '3',
    title: `Third result`,
    description: 'Yet another one.',
    url: `/media/3`,
    imageUrl: '/placeholder-3.jpg',
    type: 'audio',
    date: '2025-03-15',
  },
  {
    id: '4',
    title: `Fourth result`,
    description: 'A different placeholder.',
    url: `/media/4`,
    imageUrl: '/placeholder-4.jpg',
    type: 'image',
    date: '2025-02-10',
  },
  {
    id: '5',
    title: `Fifth result`,
    description: 'Another placeholder.',
    url: `/media/5`,
    imageUrl: '/placeholder-5.jpg',
    type: 'video',
    date: '2025-01-05',
  },
  {
    id: '6',
    title: `Sixth result`,
    description: 'Yet another one.',
    url: `/media/6`,
    imageUrl: '/placeholder-6.jpg',
    type: 'audio',
    date: '2024-12-25',
  },
  {
    id: '7',
    title: `Seventh result`,
    description: 'A different placeholder.',
    url: `/media/7`,
    imageUrl: '/placeholder-7.jpg',
    type: 'image',
    date: '2024-11-20',
  },
  {
    id: '8',
    title: `Eighth result`,
    description: 'Another placeholder.',
    url: `/media/8`,
    imageUrl: '/placeholder-8.jpg',
    type: 'video',
    date: '2024-10-15',
  },
  {
    id: '9',
    title: `Ninth result`,
    description: 'Yet another one.',
    url: `/media/9`,
    imageUrl: '/placeholder-9.jpg',
    type: 'audio',
    date: '2024-09-10',
  },
  {
    id: '10',
    title: `Tenth result`,
    description: 'A different placeholder.',
    url: `/media/10`,
    imageUrl: '/placeholder-10.jpg',
    type: 'image',
    date: '2024-08-05',
  },
  {
    id: '11',
    title: `Eleventh result`,
    description: 'Another placeholder.',
    url: `/media/11`,
    imageUrl: '/placeholder-11.jpg',
    type: 'video',
    date: '2024-07-01',
  },
  {
    id: '12',
    title: `Twelfth result`,
    description: 'Yet another one.',
    url: `/media/12`,
    imageUrl: '/placeholder-12.jpg',
    type: 'audio',
    date: '2024-06-25',
  },
]
